#!/bin/bash
echo -n "" | tee result_on_rust.pl
for f in examples/*.pl
do
    echo "% running $f" | tee -a result_on_rust.pl
    scryer-prolog -g "run([proof_step]),halt" webeye.pl "$f" | tee -a result_on_rust.pl
    echo "" | tee -a result_on_rust.pl
done
