#!/bin/bash
echo -n "" | tee result.n3p
for f in examples/*.n3p
do
    echo "% running $f" | tee -a result.n3p
    scryer-prolog -g "'idlabresearch.github.io/ns#main'([],true)" n3p.pl webeye.n3p "$f" | tee -a result.n3p
    echo "" | tee -a result.n3p
done
